// Code generated by Slice Machine. DO NOT EDIT.

import dynamic from "next/dynamic";

export const components = {
  contact_us: dynamic(() => import("./ContactUs")),
  corporate_target: dynamic(() => import("./CorporateTarget")),
  images: dynamic(() => import("./Images")),
  judora_group: dynamic(() => import("./JudoraGroup")),
  operations: dynamic(() => import("./Operations")),
  our_projects: dynamic(() => import("./OurProjects")),
};
